# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Lint, Test, and Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  ci:
    runs-on: ubuntu-latest
    defaults: 
      run: 
        working-directory: ./mock-email-client
    strategy:
      matrix:
        node: [16, 18]
    name: Angular E2E test on Node.js ${{ matrix.node }}
    
    steps:
    
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Install
        run: npm install --force

      - name: Build
        run: npm run build
    
      - name: Cypress tests
        uses: cypress-io/github-action@v6
        if: always()
        with:
          working-directory: ./mock-email-client
          start: npm run e2e
          wait-on: 'http://localhost:4200'
          browser: chrome
        env:
          CYPRESS_username: ${{secrets.CYPRESS.USERNAME}}
          CYPRESS_password: ${{secrets.CYPRESS.PASSWORD}}

      - name: Upload screenshots
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          working-directory: ./mock-email-client
          name: cypress-screenshots
          path: cypress/screenshots
    
      # - name: Build
      #   if: always()
      #   run: npm run build:ci
